// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Artemis.Storage.Migrations
{
    [DbContext(typeof(StorageContext))]
    internal class StorageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Artemis.Storage.Entities.Layer", b =>
            {
                b.Property<int>("ProfileId");

                b.Property<string>("Name");

                b.HasKey("ProfileId", "Name");

                b.ToTable("Layer");
            });

            modelBuilder.Entity("Artemis.Storage.Entities.Profile", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Name");

                b.HasKey("Id");

                b.ToTable("Profiles");
            });

            modelBuilder.Entity("Artemis.Storage.Entities.Setting", b =>
            {
                b.Property<string>("Name")
                    .ValueGeneratedOnAdd();

                b.Property<string>("Value");

                b.HasKey("Name");

                b.ToTable("Settings");
            });

            modelBuilder.Entity("Artemis.Storage.Entities.Layer", b =>
            {
                b.HasOne("Artemis.Storage.Entities.Profile", "Profile")
                    .WithMany("Layers")
                    .HasForeignKey("ProfileId")
                    .OnDelete(DeleteBehavior.Cascade);
            });
#pragma warning restore 612, 618
        }
    }
}