# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

resources:
  repositories:
  - repository: RGBdotNET
    type: github
    endpoint: github.com_SpoinkyNL
    name: DarthAffe/RGB.NET
    ref: Development
    trigger:
     branches:
       include:
         - Development

pool:
  vmImage: 'windows-latest'

variables:
  rgbSolution: '**/RGB.NET.sln'

steps:
- checkout: RGBdotNET

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(rgbSolution)'

- task: DotNetCoreCLI@2
  displayName: 'Build RGB.NET'
  inputs:
    command: 'build'
    projects: '$(rgbSolution)'
    arguments: '--configuration Release'

- task: PublishPipelineArtifact@1
  displayName: 'Upload build to Azure Pipelines'
  inputs:
    targetPath: '$(Build.SourcesDirectory)/bin/net5.0'
    artifact: 'RGB.NET development build'
    publishLocation: 'pipeline'